### ISSUE TITLE
'ControlsDetails' is imported from both 'package:flutter/src/material/stepper.dart' and 'package:fx_stepper/fx_stepper.dart'.

### ISSUE THREAD

**Issue by tomstgeorge** [kururu-abdo/fx_stepper#1]
Launching lib/main.dart on sdk gphone arm64 in debug mode...
lib/checkout.dart:31:1: Error: 'ControlsDetails' is imported from both 'package:flutter/src/material/stepper.dart' and 'package:fx_stepper/fx_stepper.dart'.
import 'package:fx_stepper/fx_stepper.dart';
^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

**Comment by kururu-abdo** [comment]
use "as"  in import statement
